python lerobot/scripts/control_robot.py \
    --robot.type=so100 \
    --control.type=record \
    --control.display_cameras=false \
    --control.fps=30 \
    --control.single_task="pick all objects from right rect into left rect" \
    --control.repo_id=junlinp/pick_cup_and_pen \
    --control.tags='["so100", "tutorial"]' \
    --control.warmup_time_s=10 \
    --control.episode_time_s=90 \
    --control.reset_time_s=20 \
    --control.num_episodes=50 \
    --control.push_to_hub=false
